{% set version = "0.4.1" %}

package:
  name: affogato
  version: {{ version }}

source:
  url: https://github.com/constantinpape/affogato/archive/{{ version }}.tar.gz
  sha256: 0f991e7a7e6639e42258e8574ad983b01e42fba7e61018f1d04a5dbf280b9cd5

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - setuptools  # [py>311]
    - xtensor >=0.26,<0.27
    - xtensor-python >=0.28,<0.29
    - libboost-headers
  run:
    - python
    - vigra

test:
  imports:
    - affogato
  source_files:
    - src/python/test/**/*.py
    - data/*.h5
  requires:
    - h5py
    - scipy
  commands:
    # - python -m unittest discover -s src/python/test -v  # [linux]
    # Reduce tests to the essential in conda CI.
    - python src/python/test/segmentation/test_mutex_watershed.py
    - python src/python/test/segmentation/test_grid_graph.py

about:
  home: https://github.com/constantinpape/affogato
  license: MIT
  license_file: LICENSE
  summary: Affinity based segmentation algorithms.

extra:
  recipe-maintainers:
    - constantinpape
    - Steffen-Wolf
