{% set version = "0.3.2" %}

package:
  name: affogato
  version: {{ version }}

source:
    url: https://github.com/constantinpape/affogato/archive/{{ version }}.tar.gz
    sha256: a79a57923105b1ab9dbf4179840dad9bdc18282797ff9b8e290ad55c9651d1a7

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make
  host:
    - python
    - numpy
    - xtensor >=0.21,<0.22
    - xtensor-python >=0.24,<0.25
    - boost-cpp
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - affogato
  source_files:
    - src/python/test/**/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/affogato
  license: MIT
  license_file: LICENSE
  summary: Affinity based segmentation algorithms.

extra:
  recipe-maintainers:
    - constantinpape
    - Steffen-Wolf
